# Generated by Django 4.1.7 on 2023-04-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=10)),
                ('des_word', models.CharField(max_length=40)),
            ],
        ),
    ]
